// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuUwLWL2fQs7i6u0knUHBUld94ZccaaGs',
    appId: '1:406470641375:web:3587af7433509e818acb6a',
    messagingSenderId: '406470641375',
    projectId: 'supervisa-7f491',
    authDomain: 'supervisa-7f491.firebaseapp.com',
    storageBucket: 'supervisa-7f491.firebasestorage.app',
    measurementId: 'G-9Q7TBTN2BW',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy0KOGXqJa_9am3Q8DAdtc4fA4ZNPA49A',
    appId: '1:406470641375:android:d0474a33d334169f8acb6a',
    messagingSenderId: '406470641375',
    projectId: 'supervisa-7f491',
    storageBucket: 'supervisa-7f491.firebasestorage.app',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXH83sHTbIumBhzvwbc-hmNLP78aGC7yI',
    appId: '1:406470641375:ios:11ad70c70d199dac8acb6a',
    messagingSenderId: '406470641375',
    projectId: 'supervisa-7f491',
    storageBucket: 'supervisa-7f491.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
